language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - os: linux
      r: 3.2.5
      r_binary_packages: digest
    - os: linux
      r: 3.3.0
    - os: osx

addons:
  apt:
    packages:
      - libpoppler-cpp-dev
